name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.5

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch required Go modules
        run: go mod tidy

      - name: Fetch required Go modules
        run: go mod download

      - name: golangci-lint install
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Lint
        run: make lint

      - name: Run Test
        run: make test

      - name: Build
        run: make build